services:
  utility-syslogview:
    container_name: utility-syslogview
    image: pierredavidbelanger/raftman
    restart: unless-stopped
    ports:
      - 514:514
      - 5514:5514
      - 8282:8282
    networks:
      default: {}
